config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles do
    resources :comments
  end
  
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :find_article, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@articles = Article.all.order("created_at DESC")
	end

	def new
		@article = current_user.articles.build
	end

	def show
		
	end 

	def create
		@article =current_user.articles.build(article_params)
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		redirect_to root_path
	end

	private

	def find_article
		@article = Article.find(params[:id])
	end
	def article_params
		params.require(:article).permit(:title, :body)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save

		if @comment.save
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def edit
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
	end

	def update
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		if @comment.update(params[:comment].permit(:comment))
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.haml
= simple_form_for @article do |f|
	=f.input :title
	=f.input :body
	=f.submit

app/views/articles/edit.html.haml
%h1 Edit Article
= render 'form'

= link_to "Cancel", article_path

app/views/articles/index.html.haml
%h1=Welcome to Magazine App
- @articles.each do |article|
	%h2= link_to article.title, article	
	%p
		Published at
		=time_ago_in_words(article.created_at)
		by author:
		=article.user.email

= link_to "New Article", new_article_path

app/views/articles/new.html.haml
%h1 New Article

= render 'form'

app/views/articles/show.html.haml
#article_content
	%h1= @article.title
	%p= @article.body
	%p
		%h3 comments
		%h3= @article.comments.count
		= render @article.comments
		%h4 Reply
		= render "comments/form"


= link_to "Edit", edit_article_path(@article)
= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are are sure want to delete this?" }
= link_to "Home", root_path

app/views/comments/_comment.html.haml
.comment
	%p= comment.comment
	%p 
		by
		=comment.user.email
		=link_to "Edit", edit_article_comment_path(comment.article, comment)
		=link_to "Delete", [comment.article, comment], method: :delete, data: { confirm: "are you sure to delete?"}

app/views/comments/_form.html.haml
=simple_form_for([@article, @article.comments.build]) do |f|
	= f.input :comment
	= f.submit

app/views/comments/edit.html.haml
%h1 Edit Comment

=simple_form_for([@article, @comment]) do |f|
	= f.input :comment
	= f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magazine App Build by HemaSundar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>